### ISSUE TITLE
Nous ajouter comme contributeurs

### ISSUE THREAD

**Issue by emchateau** [ahn-ens-lyon/synopsx#1]
Salut,
est-il possible de nous ajouter Philippe et moi comme contributeurs au répertoire de travail ?

mon compte : @emchateau
philippe : @PhilPons

**Comment by samsaidi** [comment]
Salut,

je viens de vous ajouter à l'équipe "synopsx" collaborant au répertoire; et à l'équipe propriétaire  (owner) "ahn" pour être sûre que vous puissiez contribuer au rep.
https://github.com/ahn-ens-lyon/synopsx/settings/collaboration

Jean-Phi, Maud, les droits de l'équipe "synopsx" sont-ils les mêmes que ceux de l'équipe propriétaire? 

Ensuite pour être reconnu comme "contributeurs" (comme le sont @mingarao  et @jmague ), ça se fait automatiquement au moment des "commit" il me semble.

Sam

**Comment by emchateau** [comment]
Merci beaucoup !
Pour information, tous les membres de l'équipe "synopsx" peut ajouter un utilisateur à l'équipe.

Je ne suis pas sûr qu'il faille nous ajouter à l'équipe propriétaire. D'ailleurs, il y'a je crois beaucoup trop de monde dans les owners. C'est autant de personnes qui ont les droits de détruire le répertoire.

(NB : pour citer quelqu'un dans une conversation il suffit de tapper @samsaidi et cela l'averti d'un message)

**Comment by mingarao** [comment]
Bonjour
J'ai supprimé tout le monde dans les owners sauf Emmanuel, Jean-Philippe et moi, pour éviter ce risque de détruire le rep par inadvertance. Ceci dit je pense que je vais m'enlever aussi car je ne suis pas encore assez tranquille avec git :)
Et je clos ce ticket :)
