### ISSUE TITLE
Modules non présents dans l'application lors de l'installation

### ISSUE THREAD

**Issue by emchateau** [ahn-ens-lyon/synopsx#12]
Nous venons de tester l'installation selon les indications et fourni les requêtes Xquery équivalentes.

L'application fait apparaître des erreurs lorsque l'on ne dispose pas des fichiers de l'AHN :
Il semble que les lignes 27-29 de restxq/synopsx.xqm ne soient pas nécessaires. Commenter les lignes de ces modules règle l'erreur.

**Comment by mingarao** [comment]
Il y a également le fait de bien mettre le fichier de config du projet dans la base 'config' et non dans la base du projet (dernier changement en date dans la structure globale de SynopsX)
Et pour le reste, vivement le chargement dynamique de module pour s'épargner ces "import module"...

**Comment by mingarao** [comment]
This is closed in the new code organisation and rewriting
