### ISSUE TITLE
Pas de CSS bootstrap dans le répertoire lors de l'installation

### ISSUE THREAD

**Issue by emchateau** [ahn-ens-lyon/synopsx#13]
Le répertoire Bootstrap n'est pas complet dans la distribution.
- Il paraîtrait plutôt logique qu'il s'agisse d'un sous-module git de sorte que l'utilisateur puisse le mettre à jour depuis l'entrepôt github de Bootsrap.
- Sinon, pourquoi ne pas utiliser la version "live" de Bootstrap qui éviterait d'inclure le code dans synopsx ?

**Comment by mingarao** [comment]
This is closed by calling the online ressource http://www.bootstrapcdn.com/
(But very slow sometimes...)
