### ISSUE TITLE
Utiliser les issues pour les choses à faire

### ISSUE THREAD

**Issue by emchateau** [ahn-ens-lyon/synopsx#2]
J'ai vu que @samsaidi a créé pas mal de pages dans le Wiki. C'est super !

Ne vaudrait-il pas mieux utiliser les issues de GitHub pour les tâches à réaliser (d'autant qu'on peut ensuite employer des gestionnaires de tâches comme [trello](https://trello.com) ou [Bee](http://neat.io/bee/)

Et se réserver le wiki strictement pour la documentation.

**Comment by samsaidi** [comment]
Si carrément. Le wiki c'était vraiment pour tester. Les taches (issues) et les jalons (milestones) pour s'assigner du taf et des dates butoirs c'est mieux :)
Qu'en pense le reste de l'équipe?

@emchateau et @PhilPons, pour info : vous le saviez peut-être déjà, mais tout notre wiki de travail, nos taches et notre forge étaient dans un redmine hébergé par le centre Blaise Pascal (http://forge.cbp.ens-lyon.fr/redmine/projects/ahn/wiki) inaccessible depuis l'extérieur.

**Comment by samsaidi** [comment]
(...suite) : et concernant les spécifications on avait rien de très formalisé. D'où les quelques pages de : https://github.com/ahn-ens-lyon/synopsx/wiki/UseCases. C'est une ébauche à laquelle on a commencé à travailler avec gazellefind (Severine Gedzelman) mardi. N'hésitez pas à modifier et compléter
