### ISSUE TITLE
branch cleaning

### ISSUE THREAD

**Issue by emchateau** [ahn-ens-lyon/synopsx#21]
Too many branches kill the branches !
We've planned to suppress unused branches from ahn-ens-lyon/synopsx
If you don't have any objections : we'll only keep
- [master](https://github.com/ahn-ens-lyon/synopsx/tree/master)
- [graal](https://github.com/ahn-ens-lyon/synopsx/tree/graal)
- [vendredi](https://github.com/ahn-ens-lyon/synopsx/tree/vendredi)--> renamed "constantia"
- [dev](https://github.com/ahn-ens-lyon/synopsx/tree/dev) waiting for further information

@mingarao @jmague @sboschetto @gazelleinfinland @samsaidi

**Comment by emchateau** [comment]
(sorry for the assignments message /o)

**Comment by emmamorlock** [comment]
ok pour moi !
emmanuelle
Le 03/02/2015 10:50, Emmanuel Chateau a écrit :

> Too many branches kill the branches !
> We've planned to suppress unused branches from ahn-ens-lyon/synopsx
> If you don't have any objections : we'll only keep
> - master https://github.com/ahn-ens-lyon/synopsx/tree/master
> - graal https://github.com/ahn-ens-lyon/synopsx/tree/graal
> - vendredi
>   https://github.com/ahn-ens-lyon/synopsx/tree/vendredi--> renamed
>   "constantia"
> - dev https://github.com/ahn-ens-lyon/synopsx/tree/dev waiting for
>   further information
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ahn-ens-lyon/synopsx/issues/21.

## 

Emmanuelle Morlock

## IGE CNRS - soutien aux projets d'édition TEI - humanités numériques

UMR 5189 HISoMA
http://www.hisoma.mom.fr/
04 72 71 58 40
06 85 84 69 16

## @emma_morlock

Membre du comité de coordination d'Humanistica, association francophone des Humanités numériques http://www.humanisti.ca
