### ISSUE TITLE
write default resource functions for entry points

### ISSUE THREAD

**Issue by emchateau** [ahn-ens-lyon/synopsx#27]
Write default resource functions for the different entry points in https://github.com/ahn-ens-lyon/synopsx/blob/dev/webapp/synopsx/projects/webapp.xqm
- [ ] {$project}
- [ ] {$project}/{$dataType}
- [ ] {$project}/{$dataType}/{$value}
- [ ] {$project}/{$dataType}/{$value}/{$option}

NB : for default entry points, it could be interesting to use new basex' s regex facility for restxq http://docs.basex.org/wiki/RESTXQ#Constraints

**Comment by mingarao** [comment]
Commented the default entry points because they were called in the place of the explicit entry points
/{myProject}/{myFunction} was called instead of /hyperdonat/references for example
To check...

**Comment by mingarao** [comment]
seems ok now  #54
