### ISSUE TITLE
simplify params in restxq 

### ISSUE THREAD

**Issue by emchateau** [ahn-ens-lyon/synopsx#32]
Simplify params in restxq

We already have : 
- queryParams as map(*)
- outputParams as map(*)

--> include $layout and $pattern in outputParams
--> does the model should really stay in queryParams ?

@mingarao

**Comment by mingarao** [comment]
I think the model is part of the query : for example to list texts has no sense in an ead model, but it does in a tei model @emchateau

**Comment by emchateau** [comment]
OK, @mingarao 
So it's done, we can close the issue
