### ISSUE TITLE
Normalize templates' names

### ISSUE THREAD

**Issue by mingarao** [ahn-ens-lyon/synopsx#38]
Something like 
page.xhtml
home.xhtml
mySpecialPage.xhtml
inc_defaultList.xhtml
inc_defaultItem.xhtml
inc_mySpecialList.xhtml
inc_mySpecialItem.xhtml
inc_anotherSpecialList.xhtml
inc_anotherSpecialItem.xhtml

(get rid of 'blog', 'serif'...)

**Comment by emchateau** [comment]
Ok, blogSerif was for my prototyping
Would use 'layout' for the page template

**Comment by sboschetto** [comment]
Templates name : 
defaultLayout.xhtml
home.xhtml
inc_defaultList.xhtml
inc_defaultItem.xhtml
error404.xhtml...
