### ISSUE TITLE
Handle the empty-sequence cases in 

### ISSUE THREAD

**Issue by mingarao** [ahn-ens-lyon/synopsx#57]
cf. error 

Stopped at /my/path/to/basex/webapp/synopsx/mappings/tei2html.xqm, 70/29: [XPTY0004] Cannot treat empty-sequence() as node(): ().

**Comment by emchateau** [comment]
By default, there is no reason to rise an error because it's only about serialization.

In my current version https://github.com/guidesDeParis/gdpWebapp/tree/master/mappings, i resolved the empty-sequence issue in 'htmlWrapping.xqm' like this (in the both functions) :

``` xquery
declare function wrapper($queryParams as map(*), $data as map(*), $outputParams as map(*)){
  let $meta := map:get($data, 'meta')
  let $contents := map:get($data,'content')
  let $layout := synopsx.lib.commons:getLayoutPath($queryParams, map:get($outputParams, 'layout'))
  let $wrap := fn:doc($layout)
  return $wrap update ( 
    for $text in .//@*
      where fn:starts-with($text, '{') and fn:ends-with($text, '}')
      let $key := fn:replace($text, '\{|\}', '')
      let $value := map:get($meta, $key)
      return replace value of node $text with fn:string($value),
     for $text in .//text()
       where fn:starts-with($text, '{') and fn:ends-with($text, '}')
       let $key := fn:replace($text, '\{|\}', '')
       let $value := map:get($meta, $key)
       return if ($key = 'content') 
         then replace node $text with pattern($queryParams, $data, $outputParams)
         else if ($value instance of node()* and $value != empty) 
           then replace node $text with render($outputParams, $value)
           else replace node $text with $value
     )
};
```

By the way, I really dont' understand what's the use of inject() in mappings/htmlWrapping.xqm...

**Comment by mingarao** [comment]
It's true !
You're definitly the architect :)
inject() is used not to rewrite the same code twice in wrapper and pattern
but I'm gonna try your new functions and maybe it is not usefull anymore.

**Comment by emchateau** [comment]
Just a modest art historian !

At last, I understood why you did it. And of course, it's useful.
In the current version, it's include.

**Comment by emchateau** [comment]
By the way, the new version is still waiting in a pull-request, I didn't merge it so you can review it first.
