### ISSUE TITLE
To do : choose how db is declared

### ISSUE THREAD

**Issue by mingarao** [ahn-ens-lyon/synopsx#69]
To do : choose how db is declared : in config.xml or entry points or both ? 

Then modify models.tei to handle all cases (at this time the getDB function is called in each tei function so one can't define another DB for a given entry point)

**Comment by emchateau** [comment]
getDB function is used to specify or a DB, or a path for document or collection.
I think it's difficult to call different DB in a same ressource. How would you link the different queries to each DB ? 
If necessary, dbName property could be a sequence of atomic values.

**Comment by mingarao** [comment]
Ok ;) But at this stage, we declare the db name several times : once in config.xml, but then again in the queryParams map **in each entry point**
So maybe this should become optional : if no db specified in the queryParams map in the entry point, then the default db is open (the one specified in config.xml), otherwise the db specified in the entry point is open

**Comment by emchateau** [comment]
Anyway, I think that for flexibility it's better to allow to declare at each entry point a special DB. In my use case for exemple the blog is separate of the sources.
Ok to make it optional. That would be great !

**Comment by mingarao** [comment]
this issue is now managed dynamically at /synopsx/config (config.xml is now loaded in the synopsx database when visiting the webapp root url / for the first time)
