### ISSUE TITLE
Connexions BaseX-oXygen

### ISSUE THREAD

**Issue by mingarao** [ahn-ens-lyon/synopsx#9]
Bonjour,

Personnellement j'arrive sans difficulté à connecter BaseX et oXygen pour l'accès aux ressources (http://docs.basex.org/wiki/Integrating_oXygen#Access_Database_Resources)

![basex-oxygen-accesressourceswebdav](https://cloud.githubusercontent.com/assets/6703169/2536009/fbc8bf08-b597-11e3-87c3-dc53bee46c85.png)

... mais pas pour l'exécution de requêtes (http://docs.basex.org/wiki/Integrating_oXygen#Perform_Queries)

Je ne vois pas ce que je loupe dans la config... 

![basex-oxygen-configsourcedonnees](https://cloud.githubusercontent.com/assets/6703169/2536013/00dc0a36-b598-11e3-837d-1f15258112da.png)

![basex-oxygen-configconnexion](https://cloud.githubusercontent.com/assets/6703169/2536012/fee951c0-b597-11e3-8678-6b5ff2121d0c.png)

En tout cas quand je lance ensuite une requête Xquery en choisissant la connexion que je viens de créer, j'ai cette erreur très prolixe...

![basex-oxygen-erreurexecutionxquery](https://cloud.githubusercontent.com/assets/6703169/2536014/02e15fa2-b598-11e3-8b12-0ccdcb3b6c96.png)

**Comment by emchateau** [comment]
C'est peut-être parcequ'il faut utiliser `localhost` dans la config du serveur
En effet, on interagit avec BaseX plutôt qu'avec l'application RESTXQ.

![capture decran 2014-04-02 a 08 43 26](https://cloud.githubusercontent.com/assets/818621/2588082/c9194006-ba32-11e3-9281-186e3060f179.png)

![capture decran 2014-04-02 a 08 46 04](https://cloud.githubusercontent.com/assets/818621/2588083/cf0a8470-ba32-11e3-8a69-b2f4a9e527aa.png)

Cette dernière vue d'écran concerne l'utilisation de BaseX pour la validation.

![capture decran 2014-04-02 a 08 43 42](https://cloud.githubusercontent.com/assets/818621/2588084/d3b22d02-ba32-11e3-8478-2510d963f233.png)

**Comment by mingarao** [comment]
En effet, c'était bien ça :)
Le branchement fonctionne à présent !
Je cherche maintenant la réponse à ta question (comment voir dans oXygen les informations sur la requête fournies dans la GUI BaseX : temps d'exécution, requête optimisée, etc.), et si je ne trouve pas, ce sera une question à poser à Constance :)

**Comment by mingarao** [comment]
Je me suis réjouie trop vite, la connexion est refusée.
Je ne pige pas quels id/ports/serveur il faut mettre...
A suivre...

**Comment by emchateau** [comment]
Oups, il devait manquer une vue d'écran
Je n'arrive pas à la charge avec la connexion ici.

Chez moi la config de la connexion est la suivante :
- port : 1984
- databaseName :
- readOnly :
- logLevel :
- description :
- longinTimeout :
- serverName : localhost
- user : admin
- password : ****\* [admin]
